//! Reviewed profile membership for the operations declared by the parent registry.

use super::{
    APP_CONNECTIONS_LIST_TOOL, AUDIT_LOGS_LIST_TOOL, CERTIFICATE_AUTHORITIES_LIST_TOOL,
    CERTIFICATE_POLICIES_CREATE_TOOL, CERTIFICATE_POLICIES_DELETE_TOOL,
    CERTIFICATE_POLICIES_GET_TOOL, CERTIFICATE_POLICIES_LIST_TOOL,
    CERTIFICATE_POLICIES_UPDATE_TOOL, CERTIFICATE_PROFILE_CERTIFICATES_LIST_TOOL,
    CERTIFICATE_PROFILE_EAB_SECRET_REVEAL_TOOL, CERTIFICATE_PROFILE_LATEST_BUNDLE_REVEAL_TOOL,
    CERTIFICATE_PROFILES_CREATE_TOOL, CERTIFICATE_PROFILES_DELETE_TOOL,
    CERTIFICATE_PROFILES_GET_BY_SLUG_TOOL, CERTIFICATE_PROFILES_GET_TOOL,
    CERTIFICATE_PROFILES_LIST_TOOL, CERTIFICATE_PROFILES_UPDATE_TOOL,
    CERTIFICATE_REQUEST_RESULT_REVEAL_TOOL, CERTIFICATE_REQUESTS_CANCEL_TOOL,
    CERTIFICATE_REQUESTS_GET_TOOL, CERTIFICATE_REQUESTS_LIST_TOOL, CERTIFICATES_BUNDLE_REVEAL_TOOL,
    CERTIFICATES_CERTIFICATE_GET_TOOL, CERTIFICATES_DELETE_TOOL, CERTIFICATES_GET_TOOL,
    CERTIFICATES_IMPORT_TOOL, CERTIFICATES_ISSUE_TOOL, CERTIFICATES_LIST_TOOL,
    CERTIFICATES_PRIVATE_KEY_REVEAL_TOOL, CERTIFICATES_RENEW_TOOL,
    CERTIFICATES_RENEWAL_CONFIGURATION_UPDATE_TOOL, CERTIFICATES_REVOKE_TOOL,
    CODE_SIGNER_APPROVAL_POLICY_GET_TOOL, CODE_SIGNER_APPROVAL_POLICY_REPLACE_TOOL,
    CODE_SIGNER_APPROVAL_REQUESTS_CREATE_TOOL, CODE_SIGNER_APPROVAL_REQUESTS_LIST_TOOL,
    CODE_SIGNER_APPROVAL_REQUESTS_PRE_APPROVE_TOOL, CODE_SIGNER_APPROVAL_REQUESTS_REVOKE_TOOL,
    CODE_SIGNER_EFFECTIVE_MEMBERS_LIST_TOOL, CODE_SIGNER_MEMBER_ROLE_UPDATE_TOOL,
    CODE_SIGNER_MEMBERS_ADD_TOOL, CODE_SIGNER_MEMBERS_LIST_TOOL, CODE_SIGNER_MEMBERS_REMOVE_TOOL,
    CODE_SIGNER_OPERATIONS_LIST_TOOL, CODE_SIGNER_PERMISSIONS_GET_TOOL,
    CODE_SIGNERS_CERTIFICATE_EXPORT_TOOL, CODE_SIGNERS_CERTIFICATE_REISSUE_TOOL,
    CODE_SIGNERS_CREATE_TOOL, CODE_SIGNERS_DELETE_TOOL, CODE_SIGNERS_GET_TOOL,
    CODE_SIGNERS_LIST_TOOL, CODE_SIGNERS_PUBLIC_KEY_GET_TOOL, CODE_SIGNERS_SIGN_TOOL,
    CODE_SIGNERS_STATUS_UPDATE_TOOL, CODE_SIGNERS_UPDATE_TOOL, DYNAMIC_SECRET_LEASES_CREATE_TOOL,
    DYNAMIC_SECRET_LEASES_GET_TOOL, DYNAMIC_SECRET_LEASES_LIST_TOOL,
    DYNAMIC_SECRET_LEASES_RENEW_TOOL, DYNAMIC_SECRET_LEASES_REVOKE_TOOL,
    DYNAMIC_SECRETS_CREATE_TOOL, DYNAMIC_SECRETS_DELETE_TOOL, DYNAMIC_SECRETS_GET_TOOL,
    DYNAMIC_SECRETS_LIST_TOOL, DYNAMIC_SECRETS_UPDATE_TOOL, ENVIRONMENTS_CREATE_TOOL,
    ENVIRONMENTS_DELETE_TOOL, ENVIRONMENTS_GET_TOOL, ENVIRONMENTS_LIST_TOOL,
    ENVIRONMENTS_RESTORE_TOOL, ENVIRONMENTS_UPDATE_TOOL, FOLDERS_BATCH_UPDATE_TOOL,
    FOLDERS_CREATE_TOOL, FOLDERS_DELETE_TOOL, FOLDERS_GET_TOOL, FOLDERS_LIST_TOOL,
    FOLDERS_UPDATE_TOOL, GITHUB_APP_CONNECTION_CREATE_TOOL, GITHUB_APP_CONNECTION_DELETE_TOOL,
    GITHUB_APP_CONNECTION_GET_TOOL, GITHUB_APP_CONNECTION_ROTATE_CREDENTIALS_TOOL,
    GITHUB_APP_CONNECTION_UPDATE_TOOL, GITHUB_SECRET_SYNC_CREATE_TOOL,
    GITHUB_SECRET_SYNC_DELETE_TOOL, GITHUB_SECRET_SYNC_GET_TOOL,
    GITHUB_SECRET_SYNC_REMOVE_SECRETS_TOOL, GITHUB_SECRET_SYNC_RUN_TOOL,
    GITHUB_SECRET_SYNC_UPDATE_TOOL, GROUP_MEMBERS_LIST_TOOL, GROUP_PROJECTS_LIST_TOOL,
    GROUPS_GET_TOOL, GROUPS_LIST_TOOL, IDENTITIES_CREATE_TOOL, IDENTITIES_DELETE_TOOL,
    IDENTITIES_GET_TOOL, IDENTITIES_LIST_TOOL, IDENTITIES_UPDATE_TOOL,
    IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_CREATE_TOOL,
    IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_DELETE_TOOL,
    IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_GET_BY_SLUG_TOOL,
    IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_GET_TOOL,
    IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_LIST_TOOL,
    IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_UPDATE_TOOL, INTERNAL_CA_CERTIFICATE_GENERATE_TOOL,
    INTERNAL_CA_CERTIFICATE_GET_TOOL, INTERNAL_CA_CERTIFICATE_IMPORT_TOOL,
    INTERNAL_CA_CERTIFICATE_RENEW_TOOL, INTERNAL_CA_CERTIFICATE_VERSION_GET_TOOL,
    INTERNAL_CA_CERTIFICATES_LIST_TOOL, INTERNAL_CA_CRLS_LIST_TOOL, INTERNAL_CA_CSR_GET_TOOL,
    INTERNAL_CA_INTERMEDIATE_SIGN_TOOL, INTERNAL_CERTIFICATE_AUTHORITIES_CREATE_TOOL,
    INTERNAL_CERTIFICATE_AUTHORITIES_DELETE_TOOL, INTERNAL_CERTIFICATE_AUTHORITIES_GET_TOOL,
    INTERNAL_CERTIFICATE_AUTHORITIES_LIST_TOOL, INTERNAL_CERTIFICATE_AUTHORITIES_UPDATE_TOOL,
    KMS_DECRYPT_TOOL, KMS_ENCRYPT_TOOL, KMS_KEYS_BULK_IMPORT_TOOL, KMS_KEYS_CREATE_TOOL,
    KMS_KEYS_DELETE_TOOL, KMS_KEYS_GET_BY_NAME_TOOL, KMS_KEYS_GET_TOOL, KMS_KEYS_LIST_TOOL,
    KMS_KEYS_UPDATE_TOOL, KMS_PRIVATE_KEY_REVEAL_TOOL, KMS_PRIVATE_KEYS_BULK_REVEAL_TOOL,
    KMS_PUBLIC_KEY_GET_TOOL, KMS_SIGN_TOOL, KMS_SIGNING_ALGORITHMS_LIST_TOOL, KMS_VERIFY_TOOL,
    KUBERNETES_AUTH_ATTACH_TOOL, KUBERNETES_AUTH_GET_TOOL, KUBERNETES_AUTH_REMOVE_TOOL,
    KUBERNETES_AUTH_UPDATE_TOOL, ORGANIZATION_ROLES_GET_TOOL, ORGANIZATION_ROLES_LIST_TOOL,
    PROJECT_GROUP_MEMBERSHIPS_GET_TOOL, PROJECT_GROUP_MEMBERSHIPS_LIST_TOOL,
    PROJECT_IDENTITY_MEMBERSHIPS_CREATE_TOOL, PROJECT_IDENTITY_MEMBERSHIPS_DELETE_TOOL,
    PROJECT_IDENTITY_MEMBERSHIPS_GET_TOOL, PROJECT_IDENTITY_MEMBERSHIPS_LIST_TOOL,
    PROJECT_IDENTITY_MEMBERSHIPS_UPDATE_TOOL, PROJECT_ROLES_GET_TOOL, PROJECT_ROLES_LIST_TOOL,
    PROJECT_USER_MEMBERSHIPS_DELETE_TOOL, PROJECT_USER_MEMBERSHIPS_GET_TOOL,
    PROJECT_USER_MEMBERSHIPS_INVITE_TOOL, PROJECT_USER_MEMBERSHIPS_LIST_TOOL,
    PROJECT_USER_MEMBERSHIPS_UPDATE_TOOL, PROJECTS_CREATE_TOOL, PROJECTS_DELETE_TOOL,
    PROJECTS_GET_TOOL, PROJECTS_LIST_TOOL, PROJECTS_UPDATE_TOOL, SECRET_BATCH_CREATE_TOOL,
    SECRET_BATCH_DELETE_TOOL, SECRET_BATCH_UPDATE_TOOL, SECRET_CREATE_TOOL, SECRET_DELETE_TOOL,
    SECRET_IMPORTS_CREATE_TOOL, SECRET_IMPORTS_DELETE_TOOL, SECRET_IMPORTS_GET_TOOL,
    SECRET_IMPORTS_LIST_TOOL, SECRET_IMPORTS_UPDATE_TOOL, SECRET_METADATA_LIST_TOOL,
    SECRET_REVEAL_TOOL, SECRET_ROTATIONS_LIST_TOOL, SECRET_SYNCS_LIST_TOOL, SECRET_UPDATE_TOOL,
    SQL_SECRET_ROTATION_CHECK_TOOL, SQL_SECRET_ROTATION_CREATE_TOOL,
    SQL_SECRET_ROTATION_DELETE_TOOL, SQL_SECRET_ROTATION_GENERATED_CREDENTIALS_GET_TOOL,
    SQL_SECRET_ROTATION_GET_BY_NAME_TOOL, SQL_SECRET_ROTATION_GET_TOOL,
    SQL_SECRET_ROTATION_MOVE_TOOL, SQL_SECRET_ROTATION_ROTATE_TOOL,
    SQL_SECRET_ROTATION_UPDATE_TOOL, SSH_CERTIFICATE_AUTHORITIES_CREATE_TOOL,
    SSH_CERTIFICATE_AUTHORITIES_DELETE_TOOL, SSH_CERTIFICATE_AUTHORITIES_GET_TOOL,
    SSH_CERTIFICATE_AUTHORITIES_LIST_TOOL, SSH_CERTIFICATE_AUTHORITIES_PUBLIC_KEY_GET_TOOL,
    SSH_CERTIFICATE_AUTHORITIES_REPLACE_TOOL, SSH_CERTIFICATE_AUTHORITY_TEMPLATES_LIST_TOOL,
    SSH_CERTIFICATE_TEMPLATES_CREATE_TOOL, SSH_CERTIFICATE_TEMPLATES_DELETE_TOOL,
    SSH_CERTIFICATE_TEMPLATES_GET_TOOL, SSH_CERTIFICATE_TEMPLATES_LIST_TOOL,
    SSH_CERTIFICATE_TEMPLATES_REPLACE_TOOL, SSH_CERTIFICATES_ISSUE_TOOL,
    SSH_CERTIFICATES_SIGN_TOOL, SSH_HOST_GROUP_HOSTS_ADD_TOOL, SSH_HOST_GROUP_HOSTS_LIST_TOOL,
    SSH_HOST_GROUP_HOSTS_REMOVE_TOOL, SSH_HOST_GROUPS_CREATE_TOOL, SSH_HOST_GROUPS_DELETE_TOOL,
    SSH_HOST_GROUPS_GET_TOOL, SSH_HOST_GROUPS_LIST_TOOL, SSH_HOST_GROUPS_REPLACE_TOOL,
    SSH_HOSTS_CREATE_TOOL, SSH_HOSTS_DELETE_TOOL, SSH_HOSTS_GET_TOOL,
    SSH_HOSTS_HOST_CA_PUBLIC_KEY_GET_TOOL, SSH_HOSTS_HOST_CERTIFICATE_ISSUE_TOOL,
    SSH_HOSTS_LIST_TOOL, SSH_HOSTS_REPLACE_TOOL, SSH_HOSTS_USER_CA_PUBLIC_KEY_GET_TOOL,
    TAGS_CREATE_TOOL, TAGS_DELETE_TOOL, TAGS_GET_TOOL, TAGS_LIST_TOOL, TAGS_UPDATE_TOOL,
    TOKEN_AUTH_ATTACH_TOOL, TOKEN_AUTH_GET_TOOL, TOKEN_AUTH_REMOVE_TOOL,
    TOKEN_AUTH_TOKENS_CREATE_TOOL, TOKEN_AUTH_TOKENS_GET_TOOL, TOKEN_AUTH_TOKENS_LIST_TOOL,
    TOKEN_AUTH_TOKENS_REVOKE_TOOL, TOKEN_AUTH_TOKENS_UPDATE_TOOL, TOKEN_AUTH_UPDATE_TOOL,
    UNIVERSAL_AUTH_ATTACH_TOOL, UNIVERSAL_AUTH_CLIENT_SECRETS_CREATE_TOOL,
    UNIVERSAL_AUTH_CLIENT_SECRETS_GET_TOOL, UNIVERSAL_AUTH_CLIENT_SECRETS_LIST_TOOL,
    UNIVERSAL_AUTH_CLIENT_SECRETS_REVOKE_TOOL, UNIVERSAL_AUTH_GET_TOOL,
    UNIVERSAL_AUTH_LOCKOUTS_CLEAR_TOOL, UNIVERSAL_AUTH_REMOVE_TOOL, UNIVERSAL_AUTH_UPDATE_TOOL,
};
use crate::policy::PolicyFacts;

#[allow(clippy::too_many_lines)]
pub(super) fn facts(name: &str) -> PolicyFacts {
    let (metadata, secrets, pki_ssh, credential_disclosure) = match name {
        GITHUB_APP_CONNECTION_CREATE_TOOL
        | GITHUB_APP_CONNECTION_DELETE_TOOL
        | GITHUB_APP_CONNECTION_ROTATE_CREDENTIALS_TOOL
        | GITHUB_APP_CONNECTION_UPDATE_TOOL
        | ENVIRONMENTS_CREATE_TOOL
        | ENVIRONMENTS_DELETE_TOOL
        | ENVIRONMENTS_RESTORE_TOOL
        | ENVIRONMENTS_UPDATE_TOOL
        | IDENTITIES_CREATE_TOOL
        | IDENTITIES_DELETE_TOOL
        | IDENTITIES_UPDATE_TOOL
        | KUBERNETES_AUTH_ATTACH_TOOL
        | KUBERNETES_AUTH_REMOVE_TOOL
        | KUBERNETES_AUTH_UPDATE_TOOL
        | IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_CREATE_TOOL
        | IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_DELETE_TOOL
        | IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_UPDATE_TOOL
        | TOKEN_AUTH_ATTACH_TOOL
        | TOKEN_AUTH_REMOVE_TOOL
        | TOKEN_AUTH_TOKENS_REVOKE_TOOL
        | TOKEN_AUTH_TOKENS_UPDATE_TOOL
        | TOKEN_AUTH_UPDATE_TOOL
        | UNIVERSAL_AUTH_ATTACH_TOOL
        | UNIVERSAL_AUTH_CLIENT_SECRETS_REVOKE_TOOL
        | UNIVERSAL_AUTH_LOCKOUTS_CLEAR_TOOL
        | UNIVERSAL_AUTH_REMOVE_TOOL
        | UNIVERSAL_AUTH_UPDATE_TOOL
        | KMS_ENCRYPT_TOOL
        | KMS_KEYS_BULK_IMPORT_TOOL
        | KMS_KEYS_CREATE_TOOL
        | KMS_KEYS_DELETE_TOOL
        | KMS_KEYS_UPDATE_TOOL
        | KMS_SIGN_TOOL
        | KMS_VERIFY_TOOL
        | PROJECT_IDENTITY_MEMBERSHIPS_CREATE_TOOL
        | PROJECT_IDENTITY_MEMBERSHIPS_DELETE_TOOL
        | PROJECT_IDENTITY_MEMBERSHIPS_UPDATE_TOOL
        | PROJECT_USER_MEMBERSHIPS_DELETE_TOOL
        | PROJECT_USER_MEMBERSHIPS_INVITE_TOOL
        | PROJECT_USER_MEMBERSHIPS_UPDATE_TOOL
        | PROJECTS_CREATE_TOOL
        | PROJECTS_DELETE_TOOL
        | PROJECTS_UPDATE_TOOL => (false, false, false, false),
        GITHUB_APP_CONNECTION_GET_TOOL
        | APP_CONNECTIONS_LIST_TOOL
        | AUDIT_LOGS_LIST_TOOL
        | GROUPS_GET_TOOL
        | GROUPS_LIST_TOOL
        | GROUP_MEMBERS_LIST_TOOL
        | GROUP_PROJECTS_LIST_TOOL
        | IDENTITIES_GET_TOOL
        | IDENTITIES_LIST_TOOL
        | KUBERNETES_AUTH_GET_TOOL
        | IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_GET_TOOL
        | IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_GET_BY_SLUG_TOOL
        | IDENTITY_PROJECT_ADDITIONAL_PRIVILEGES_LIST_TOOL
        | TOKEN_AUTH_GET_TOOL
        | TOKEN_AUTH_TOKENS_GET_TOOL
        | TOKEN_AUTH_TOKENS_LIST_TOOL
        | UNIVERSAL_AUTH_CLIENT_SECRETS_GET_TOOL
        | UNIVERSAL_AUTH_CLIENT_SECRETS_LIST_TOOL
        | UNIVERSAL_AUTH_GET_TOOL
        | KMS_KEYS_GET_TOOL
        | KMS_KEYS_GET_BY_NAME_TOOL
        | KMS_KEYS_LIST_TOOL
        | KMS_PUBLIC_KEY_GET_TOOL
        | KMS_SIGNING_ALGORITHMS_LIST_TOOL
        | ORGANIZATION_ROLES_GET_TOOL
        | ORGANIZATION_ROLES_LIST_TOOL
        | PROJECT_GROUP_MEMBERSHIPS_GET_TOOL
        | PROJECT_GROUP_MEMBERSHIPS_LIST_TOOL
        | PROJECT_IDENTITY_MEMBERSHIPS_GET_TOOL
        | PROJECT_IDENTITY_MEMBERSHIPS_LIST_TOOL
        | PROJECT_ROLES_GET_TOOL
        | PROJECT_ROLES_LIST_TOOL
        | PROJECT_USER_MEMBERSHIPS_GET_TOOL
        | PROJECT_USER_MEMBERSHIPS_LIST_TOOL => (true, false, false, false),
        INTERNAL_CA_CERTIFICATE_GENERATE_TOOL
        | INTERNAL_CA_CERTIFICATE_IMPORT_TOOL
        | INTERNAL_CA_CERTIFICATE_RENEW_TOOL
        | INTERNAL_CERTIFICATE_AUTHORITIES_CREATE_TOOL
        | INTERNAL_CERTIFICATE_AUTHORITIES_DELETE_TOOL
        | INTERNAL_CA_INTERMEDIATE_SIGN_TOOL
        | INTERNAL_CERTIFICATE_AUTHORITIES_UPDATE_TOOL
        | CERTIFICATE_POLICIES_CREATE_TOOL
        | CERTIFICATE_POLICIES_DELETE_TOOL
        | CERTIFICATE_POLICIES_UPDATE_TOOL
        | CERTIFICATE_PROFILES_CREATE_TOOL
        | CERTIFICATE_PROFILES_DELETE_TOOL
        | CERTIFICATE_PROFILES_UPDATE_TOOL
        | CERTIFICATE_REQUESTS_CANCEL_TOOL
        | CERTIFICATES_DELETE_TOOL
        | CERTIFICATES_IMPORT_TOOL
        | CERTIFICATES_RENEWAL_CONFIGURATION_UPDATE_TOOL
        | CERTIFICATES_REVOKE_TOOL
        | CODE_SIGNER_APPROVAL_POLICY_REPLACE_TOOL
        | CODE_SIGNER_APPROVAL_REQUESTS_CREATE_TOOL
        | CODE_SIGNER_APPROVAL_REQUESTS_PRE_APPROVE_TOOL
        | CODE_SIGNER_APPROVAL_REQUESTS_REVOKE_TOOL
        | CODE_SIGNERS_CERTIFICATE_REISSUE_TOOL
        | CODE_SIGNERS_CREATE_TOOL
        | CODE_SIGNERS_DELETE_TOOL
        | CODE_SIGNER_MEMBERS_ADD_TOOL
        | CODE_SIGNER_MEMBERS_REMOVE_TOOL
        | CODE_SIGNER_MEMBER_ROLE_UPDATE_TOOL
        | CODE_SIGNERS_SIGN_TOOL
        | CODE_SIGNERS_STATUS_UPDATE_TOOL
        | CODE_SIGNERS_UPDATE_TOOL
        | SSH_CERTIFICATE_AUTHORITIES_CREATE_TOOL
        | SSH_CERTIFICATE_AUTHORITIES_DELETE_TOOL
        | SSH_CERTIFICATE_AUTHORITIES_REPLACE_TOOL
        | SSH_CERTIFICATE_TEMPLATES_CREATE_TOOL
        | SSH_CERTIFICATE_TEMPLATES_DELETE_TOOL
        | SSH_CERTIFICATE_TEMPLATES_REPLACE_TOOL
        | SSH_CERTIFICATES_SIGN_TOOL
        | SSH_HOST_GROUPS_CREATE_TOOL
        | SSH_HOST_GROUPS_DELETE_TOOL
        | SSH_HOST_GROUP_HOSTS_ADD_TOOL
        | SSH_HOST_GROUP_HOSTS_REMOVE_TOOL
        | SSH_HOST_GROUPS_REPLACE_TOOL
        | SSH_HOSTS_CREATE_TOOL
        | SSH_HOSTS_DELETE_TOOL
        | SSH_HOSTS_HOST_CERTIFICATE_ISSUE_TOOL
        | SSH_HOSTS_REPLACE_TOOL => (false, false, true, false),
        INTERNAL_CA_CERTIFICATE_GET_TOOL
        | INTERNAL_CA_CERTIFICATE_VERSION_GET_TOOL
        | INTERNAL_CA_CERTIFICATES_LIST_TOOL
        | INTERNAL_CA_CRLS_LIST_TOOL
        | INTERNAL_CA_CSR_GET_TOOL
        | INTERNAL_CERTIFICATE_AUTHORITIES_GET_TOOL
        | INTERNAL_CERTIFICATE_AUTHORITIES_LIST_TOOL
        | CERTIFICATE_AUTHORITIES_LIST_TOOL
        | CERTIFICATE_POLICIES_GET_TOOL
        | CERTIFICATE_POLICIES_LIST_TOOL
        | CERTIFICATE_PROFILE_CERTIFICATES_LIST_TOOL
        | CERTIFICATE_PROFILES_GET_TOOL
        | CERTIFICATE_PROFILES_GET_BY_SLUG_TOOL
        | CERTIFICATE_PROFILES_LIST_TOOL
        | CERTIFICATE_REQUESTS_GET_TOOL
        | CERTIFICATE_REQUESTS_LIST_TOOL
        | CERTIFICATES_CERTIFICATE_GET_TOOL
        | CERTIFICATES_GET_TOOL
        | CERTIFICATES_LIST_TOOL
        | CODE_SIGNER_APPROVAL_POLICY_GET_TOOL
        | CODE_SIGNER_APPROVAL_REQUESTS_LIST_TOOL
        | CODE_SIGNERS_CERTIFICATE_EXPORT_TOOL
        | CODE_SIGNER_EFFECTIVE_MEMBERS_LIST_TOOL
        | CODE_SIGNERS_GET_TOOL
        | CODE_SIGNERS_LIST_TOOL
        | CODE_SIGNER_MEMBERS_LIST_TOOL
        | CODE_SIGNER_OPERATIONS_LIST_TOOL
        | CODE_SIGNER_PERMISSIONS_GET_TOOL
        | CODE_SIGNERS_PUBLIC_KEY_GET_TOOL
        | SSH_CERTIFICATE_AUTHORITIES_GET_TOOL
        | SSH_CERTIFICATE_AUTHORITIES_LIST_TOOL
        | SSH_CERTIFICATE_AUTHORITIES_PUBLIC_KEY_GET_TOOL
        | SSH_CERTIFICATE_AUTHORITY_TEMPLATES_LIST_TOOL
        | SSH_CERTIFICATE_TEMPLATES_GET_TOOL
        | SSH_CERTIFICATE_TEMPLATES_LIST_TOOL
        | SSH_HOST_GROUPS_GET_TOOL
        | SSH_HOST_GROUP_HOSTS_LIST_TOOL
        | SSH_HOST_GROUPS_LIST_TOOL
        | SSH_HOSTS_GET_TOOL
        | SSH_HOSTS_HOST_CA_PUBLIC_KEY_GET_TOOL
        | SSH_HOSTS_LIST_TOOL
        | SSH_HOSTS_USER_CA_PUBLIC_KEY_GET_TOOL => (true, false, true, false),
        CERTIFICATE_PROFILE_EAB_SECRET_REVEAL_TOOL
        | CERTIFICATE_PROFILE_LATEST_BUNDLE_REVEAL_TOOL
        | CERTIFICATE_REQUEST_RESULT_REVEAL_TOOL
        | CERTIFICATES_BUNDLE_REVEAL_TOOL
        | CERTIFICATES_ISSUE_TOOL
        | CERTIFICATES_PRIVATE_KEY_REVEAL_TOOL
        | CERTIFICATES_RENEW_TOOL
        | SSH_CERTIFICATES_ISSUE_TOOL => (false, false, true, true),
        DYNAMIC_SECRET_LEASES_CREATE_TOOL
        | SQL_SECRET_ROTATION_GENERATED_CREDENTIALS_GET_TOOL
        | SECRET_REVEAL_TOOL => (false, true, false, true),
        DYNAMIC_SECRET_LEASES_GET_TOOL
        | DYNAMIC_SECRET_LEASES_LIST_TOOL
        | DYNAMIC_SECRETS_GET_TOOL
        | DYNAMIC_SECRETS_LIST_TOOL
        | FOLDERS_GET_TOOL
        | FOLDERS_LIST_TOOL
        | SECRET_IMPORTS_GET_TOOL
        | SECRET_IMPORTS_LIST_TOOL
        | SECRET_ROTATIONS_LIST_TOOL
        | SQL_SECRET_ROTATION_GET_TOOL
        | SQL_SECRET_ROTATION_GET_BY_NAME_TOOL
        | GITHUB_SECRET_SYNC_GET_TOOL
        | SECRET_SYNCS_LIST_TOOL
        | SECRET_METADATA_LIST_TOOL
        | TAGS_GET_TOOL
        | TAGS_LIST_TOOL => (true, true, false, false),
        DYNAMIC_SECRET_LEASES_RENEW_TOOL
        | DYNAMIC_SECRET_LEASES_REVOKE_TOOL
        | DYNAMIC_SECRETS_CREATE_TOOL
        | DYNAMIC_SECRETS_DELETE_TOOL
        | DYNAMIC_SECRETS_UPDATE_TOOL
        | FOLDERS_BATCH_UPDATE_TOOL
        | FOLDERS_CREATE_TOOL
        | FOLDERS_DELETE_TOOL
        | FOLDERS_UPDATE_TOOL
        | SECRET_IMPORTS_CREATE_TOOL
        | SECRET_IMPORTS_DELETE_TOOL
        | SECRET_IMPORTS_UPDATE_TOOL
        | SQL_SECRET_ROTATION_CHECK_TOOL
        | SQL_SECRET_ROTATION_CREATE_TOOL
        | SQL_SECRET_ROTATION_DELETE_TOOL
        | SQL_SECRET_ROTATION_MOVE_TOOL
        | SQL_SECRET_ROTATION_ROTATE_TOOL
        | SQL_SECRET_ROTATION_UPDATE_TOOL
        | GITHUB_SECRET_SYNC_CREATE_TOOL
        | GITHUB_SECRET_SYNC_DELETE_TOOL
        | GITHUB_SECRET_SYNC_REMOVE_SECRETS_TOOL
        | GITHUB_SECRET_SYNC_RUN_TOOL
        | GITHUB_SECRET_SYNC_UPDATE_TOOL
        | SECRET_BATCH_CREATE_TOOL
        | SECRET_BATCH_DELETE_TOOL
        | SECRET_BATCH_UPDATE_TOOL
        | SECRET_CREATE_TOOL
        | SECRET_DELETE_TOOL
        | SECRET_UPDATE_TOOL
        | TAGS_CREATE_TOOL
        | TAGS_DELETE_TOOL
        | TAGS_UPDATE_TOOL => (false, true, false, false),
        ENVIRONMENTS_GET_TOOL | ENVIRONMENTS_LIST_TOOL | PROJECTS_GET_TOOL | PROJECTS_LIST_TOOL => {
            (true, true, true, false)
        }
        TOKEN_AUTH_TOKENS_CREATE_TOOL
        | UNIVERSAL_AUTH_CLIENT_SECRETS_CREATE_TOOL
        | KMS_DECRYPT_TOOL
        | KMS_PRIVATE_KEYS_BULK_REVEAL_TOOL
        | KMS_PRIVATE_KEY_REVEAL_TOOL => (false, false, false, true),
        // New operations remain full-administration only until their policy is reviewed.
        _ => {
            return PolicyFacts {
                reviewed: false,
                metadata: false,
                secrets: false,
                pki_ssh: false,
                credential_disclosure: true,
            };
        }
    };
    PolicyFacts {
        reviewed: true,
        metadata,
        secrets,
        pki_ssh,
        credential_disclosure,
    }
}
